$\sigma \alpha \nabl$a

In [2]:
import torch
# from torch import tensor

# GPU가 존재하면 텐서를 이동합니다
print(torch.cuda.is_available())

True


In [3]:
if []: 
	print("참") 
else: 
	print("거짓")

거짓


In [4]:
a = [1, 2, 3]
b = a
id(a)
id(b)

a is b

True

In [5]:
class animal:
    pass

man = animal()
print(type(man))

<class '__main__.animal'>


In [6]:
import time

def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"{func.__name__} 실행 시간: {end_time - start_time:.4f}초")
        return result
    return wrapper

@timer
def long_task():
    time.sleep(1)
    print("작업 완료!")

long_task()

작업 완료!
long_task 실행 시간: 1.0004초


In [7]:
import dis

def my_function():
    x = 10
    y = 20
    return x + y

dis.dis(my_function)

  3           0 RESUME                   0

  4           2 LOAD_CONST               1 (10)
              4 STORE_FAST               0 (x)

  5           6 LOAD_CONST               2 (20)
              8 STORE_FAST               1 (y)

  6          10 LOAD_FAST                0 (x)
             12 LOAD_FAST                1 (y)
             14 BINARY_OP                0 (+)
             18 RETURN_VALUE


In [9]:
import torch
import numpy as pd

# 파이썬 리스트의 중첩형태에서 바로 tensor 생성 가능 
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data
print(type(x_data))

<class 'torch.Tensor'>


In [10]:
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [11]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [12]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.3369, 0.7319],
        [0.0755, 0.9117]]) 



In [13]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5186, 0.8614, 0.3405],
        [0.9295, 0.5898, 0.8818]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
# Tensor's Attribute
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
  tensor = tensor.to('cuda') # 연산에 대한 대상 메모리 위치를 옴김.
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [18]:
tensor = torch.ones(4, 4)
print(tensor)
# tensor[:,1] = 0
# print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [21]:

# element-wise product

# 요소별 곱(element-wise product)을 계산합니다
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 다른 문법:
print(f"tensor * tensor \n {tensor * tensor}")


# matrix multiplication
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# 다른 문법:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

tensor @ tensor.T 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [22]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [2]:
import torch

vector = torch.tensor([5.0, 7.0])

L1_norm = torch.norm(vector,p=1)
L2_norm = torch.norm(vector,p=2)

print(f"L1 norm : {L1_norm}")
print(f"L2 norm : {L2_norm}")

L1 norm : 12.0
L2 norm : 8.602325439453125


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")
